name: process_collection_test
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: PDF fix
        run: sudo mv /etc/ImageMagick-6/policy.xml /etc/ImageMagick-6/policy.xml.off && sudo apt-get update && sudo apt-get install -y ghostscript-x
      - name: install
        run: gem install bundler && bundle
      - name: pages
        run: bundle exec rake wax:pages test
      - name: derivatives
        run: bundle exec rake wax:derivatives:iiif test
      - name: search
        run: bundle exec rake wax:search main
      - name: update exhibit
        continue-on-error: true
        run: |
          rm pages/collection.md && touch pages/collection.md && echo -e "---\nlayout: page\ntitle: Browse the Collection\npermalink: /collection/\n---\n{% include collection_gallery.html collection='test' facet_by='object_type' %}" >> pages/collection.md
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "process wax collection test" -a
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  
